#!/bin/sh
INSTALL_PATH=/opt/bookbinder
GEM_PATH=$INSTALL_PATH/embedded/lib/ruby/gems/2.1.0
PATH=$INSTALL_PATH/embedded/bin:$PATH
RUBY=$INSTALL_PATH/embedded/bin/ruby


if [ $1 = "stage" ]; then
  
  cd final_app && $RUBY app.rb

else 
 
  $RUBY $INSTALL_PATH/bin/bookbinder-wrapper.rb "$@"

fi
