#!/opt/bookbinder/embedded/bin/ruby
#
# Adapted from a bunder-generated script
#

require 'pathname'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path("../Gemfile", Pathname.new(__FILE__).realpath)

require 'rubygems'
require 'bundler/setup'

load Gem.bin_path('bookbindery', 'bookbinder')
