source 'http://rubygems.org'

gem 'bookbindery', git: 'https://github.com/pivotal-cf/docs-bookbinder'

group :development do
  gem 'hologram', github: 'substantial/hologram'
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-livereload'
  gem 'guard-shell'
end
